### PR TITLE
Add release notes for v2.8.0.0

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Add release notes for 2.8.0.0
 
### Issues Resolved

https://github.com/opensearch-project/job-scheduler/issues/388

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dbwiddis — APPROVED** [review]

**Comment by cwperks** [comment]
@dbwiddis Can you re-start the CI?

**Review by joshpalis — APPROVED** [review]

**Comment by joshpalis** [comment]
@cwperks do we want to backport this to 2.x?

**Comment by cwperks** [comment]
Yes and to 2.8 as well.

**Comment by joshpalis** [comment]
Alright I added the backport 2.x label, can you raise another PR against 2.8?

**Pull request merged**
