### PR TITLE
Added groupId as org.opensearch.plugin in pluginZip publication

### PR DESCRIPTION
**Pull request by prudhvigodithi**
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>

### Description
Added groupId as org.opensearch.plugin in pluginZip publication
 
### Issues Resolved
https://github.com/opensearch-project/job-scheduler/issues/225
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshpalis — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Sure @saratvemulapalli  I do see the error `> Task :integTest FAILED` which is not related to this change, @joshpalis can you please confirm that?

**Comment by joshpalis** [comment]
@prudhvigodithi Integration and BWC tests have passed locally for me, might just be a flaky test but re-running the failed jobs have also failed. I shall spend some time digging into this.

**Comment by saratvemulapalli** [comment]
@prudhvigodithi @joshpalis this commit on OpenSearch could have broken the changes[1].
Looks like org.apache.http was updated to a newer version which is why its failing. 

[1]https://github.com/opensearch-project/OpenSearch/pull/4459/files

**Comment by saratvemulapalli** [comment]
I was able to re-produce the problem on local box.

```
/gradlew :opensearch-job-scheduler-sample-extension:compileTestJava
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.5.1
  OS Info               : Linux 5.4.0-1037-aws (amd64)
  JDK Version           : 14 (Private Build JDK)
  JAVA_HOME             : /usr/lib/jvm/java-14-openjdk-amd64
  Random Testing Seed   : 990C0B537CE645E9
  In FIPS 140 mode      : false
=======================================

> Task :opensearch-job-scheduler-sample-extension:compileTestJava
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:8: error: package org.apache.http does not exist
import org.apache.http.Header;
                      ^
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:9: error: package org.apache.http does not exist
import org.apache.http.HttpEntity;
                      ^
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:10: error: package org.apache.http.entity does not exist
import org.apache.http.entity.ContentType;
                             ^
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:11: error: package org.apache.http.entity does not exist
import org.apache.http.entity.StringEntity;
                             ^
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:84: error: cannot find symbol
                                   HttpEntity entity, Header... headers) throws IOException {
                                   ^
  symbol:   class HttpEntity
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:84: error: cannot find symbol
                                   HttpEntity entity, Header... headers) throws IOException {
                                                      ^
  symbol:   class Header
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:62: error: cannot find symbol
                new StringEntity(jobParameter, ContentType.APPLICATION_JSON));
                    ^
  symbol:   class StringEntity
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:62: error: cannot find symbol
                new StringEntity(jobParameter, ContentType.APPLICATION_JSON));
                                               ^
  symbol:   variable ContentType
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:89: error: cannot find symbol
        for (Header header: headers) {
             ^
  symbol:   class Header
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:165: error: cannot find symbol
                Collections.emptyMap(), new StringEntity(entity, ContentType.APPLICATION_JSON));
                                            ^
  symbol:   class StringEntity
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:165: error: cannot find symbol
                Collections.emptyMap(), new StringEntity(entity, ContentType.APPLICATION_JSON));
                                                                 ^
  symbol:   variable ContentType
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:242: error: cannot find symbol
                Collections.emptyMap(), new StringEntity(entity, ContentType.APPLICATION_JSON));
                                            ^
  symbol:   class StringEntity
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:242: error: cannot find symbol
                Collections.emptyMap(), new StringEntity(entity, ContentType.APPLICATION_JSON));
                                                                 ^
  symbol:   variable ContentType
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:265: error: cannot find symbol
                Collections.emptyMap(), new StringEntity(entity, ContentType.APPLICATION_JSON));
                                            ^
  symbol:   class StringEntity
  location: class SampleExtensionIntegTestCase
/home/ubuntu/prudhvi-groupId-js/sample-extension-plugin/src/test/java/org/opensearch/jobscheduler/sampleextension/SampleExtensionIntegTestCase.java:265: error: cannot find symbol
                Collections.emptyMap(), new StringEntity(entity, ContentType.APPLICATION_JSON));
                                                                 ^
  symbol:   variable ContentType
  location: class SampleExtensionIntegTestCase
15 errors

> Task :opensearch-job-scheduler-sample-extension:compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':opensearch-job-scheduler-sample-extension:compileTestJava'.
> Compilation failed; see the compiler error output for details.
```

**Comment by joshpalis** [comment]
@prudhvigodithi I will raise a PR later today to modify the org.apache.http imports. Once this change is merged, please rebase your fork with JS main and the failing tests should be resolved.

**Comment by saratvemulapalli** [comment]
@prudhvigodithi could you rebase your changes with main, this should get CIs to pass.

**Comment by prudhvigodithi** [comment]
Hey @saratvemulapalli and @joshpalis  and I just did 👍

**Review by joshpalis — APPROVED** [review]

**Review by saratvemulapalli — APPROVED** [review]

**Pull request merged**
