### PR TITLE
Update to Gradle 8.0.2

### PR DESCRIPTION
**Pull request by cwperks**
### Description

Starting a draft pull request to understand required efforts for migration to gradle 8. Reference PR from core: https://github.com/opensearch-project/OpenSearch/pull/5666
 
### Issues Resolved

N/A
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dbwiddis — APPROVED** [review]
Can we set this repo up to do version bumps with Mend Renovate?

**Comment by dbwiddis** [comment]
Any reason we're holding off on this merge?

**Comment by cwperks** [comment]
I don't have the ability to merge PRs in this repo

**Comment by joshpalis** [comment]
@dbwiddis lets hold off on merging until https://github.com/opensearch-project/job-scheduler/issues/350 is resolved. Currently 2.x is broken, which is used for 3.0.0 BWC tests. Once the issue is resolved today, I'll merge in this PR to main

**Comment by joshpalis** [comment]
Will re-run checks and merge this in once there is a successful 2.7.0 distribution opensearch build. Currently the tests are failing due to :

```
Could not determine the dependencies of task ':opensearch-job-scheduler-sample-extension:jobSchedulerBwcCluster#fullRestartClusterTask'.
> Server returned HTTP response code: 403 for URL: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7336/linux/x64/tar/builds/opensearch/plugins/opensearch-job-scheduler-2.7.0.0.zip
```

**Comment by dbwiddis** [comment]
If it's going to be a long time until the upgrade, can we at least bump to 7.6+?  The current config is 7.5 which is not compatible with JDK 19+.

**Comment by joshpalis** [comment]
@dbwiddis Shouldn't take long. 2.7.0 distribution opensearch builds have been failing due to neural search but I see that this issue has been called out and will probably be resolved today. Either way, we won't be able to merge any change in until a successful build has been generated.

**Comment by cwperks** [comment]
@joshpalis Yes, this should be backported.

**Comment by cwperks** [comment]
I can create a manual backport

**Comment by cwperks** [comment]
@joshpalis I created a backport PR to 2.x for this change: https://github.com/opensearch-project/job-scheduler/pull/357

**Comment by joshpalis** [comment]
@cwperks seems that upgrading gradle to 8.0.2 has broken the maven publish snapshots workflow. Snapshots for 3.x and 2.x have not been updated since March 28th

see https://github.com/opensearch-project/job-scheduler/actions/runs/4600506610/jobs/8127183785

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':generatePomFileForPluginZipPublication' (type 'GenerateMavenPom').
  - Gradle detected a problem with the following location: '/home/runner/work/job-scheduler/job-scheduler/build/distributions/opensearch-job-scheduler-3.0.0.0-SNAPSHOT.pom'.
    
    Reason: Task ':publishNebulaPublicationToSnapshotsRepository' uses this output of task ':generatePomFileForPluginZipPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':generatePomFileForPluginZipPublication' as an input of ':publishNebulaPublicationToSnapshotsRepository'.
      2. Declare an explicit dependency on ':generatePomFileForPluginZipPublication' from ':publishNebulaPublicationToSnapshotsRepository' using Task#dependsOn.
      3. Declare an explicit dependency on ':generatePomFileForPluginZipPublication' from ':publishNebulaPublicationToSnapshotsRepository' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

**Pull request merged**
