### PR TITLE
Staging for version increment automation

### PR DESCRIPTION
**Pull request by prudhvigodithi**
Signed-off-by: pgodithi <pgodithi@amazon.com>

### Description
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/job-scheduler/pull/1
 
### Issues Resolved
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/job-scheduler/issues/197
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Sample PR
`job-scheduler main : OpenSearch main`  
https://github.com/prudhvigodithi/job-scheduler/pull/2/files

**Comment by prudhvigodithi** [comment]
Renaming to task `updateVersion` following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

**Comment by prudhvigodithi** [comment]
Hey @dblock can you please take a look.
Thank you

**Comment by bbarani** [comment]
@downsrob  @praveensameneni can you please review this PR soon?

**Review by dblock — APPROVED** [review]

**Review by VachaShah — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Hey All can we please review and merge the following backport PR's?
https://github.com/opensearch-project/job-scheduler/pull/209
https://github.com/opensearch-project/job-scheduler/pull/210
https://github.com/opensearch-project/job-scheduler/pull/211
https://github.com/opensearch-project/job-scheduler/pull/212
https://github.com/opensearch-project/job-scheduler/pull/213

**Pull request merged**
