### PR TITLE
Consuming breaking changes from moving ExtensionActionRequest

### PR DESCRIPTION
**Pull request by saratvemulapalli**
### Description
Companion PR of: https://github.com/opensearch-project/OpenSearch/pull/7468 as the signature of API changed. 
 
### Issues Resolved
Unblocks: https://github.com/opensearch-project/anomaly-detection/actions/runs/4929882106/jobs/8810089919?pr=890
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by owaiskazi19 — APPROVED** [review]

**Comment by saratvemulapalli** [comment]
I can confirm tests on AD extension pass.

```
vemsarat@anomaly-detection % ./gradlew check
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.1.1
  OS Info               : Mac OS X 10.16 (x86_64)
  JDK Version           : 14 (Oracle JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home
  Random Testing Seed   : 384EB48E486BAD0F
  In FIPS 140 mode      : false
=======================================

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.powermock.reflect.internal.WhiteboxImpl (file:/Users/vemsarat/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-reflect/2.0.7/9a8b85397c5a72923962ee9e6bf774e8458803bb/powermock-reflect-2.0.7.jar) to method java.util.Arrays.rangeCheck(int,int,int)
WARNING: Please consider reporting this to the maintainers of org.powermock.reflect.internal.WhiteboxImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :spotlessJava
Skipping '/Users/vemsarat/Desktop/workspace/Code/anomaly-detection/src/test/java/org/opensearch/search/aggregations/metrics/CardinalityProfileTests.java' because it does not converge.  Run {@code spotlessDiagnose} to understand why

BUILD SUCCESSFUL in 1m 28s
10 actionable tasks: 6 executed, 4 up-to-date
vemsarat@anomaly-detection % 
```

**Review by vibrantvarun — APPROVED** [review]
LGTM

**Review by joshpalis — APPROVED** [review]

**Comment by joshpalis** [comment]
@saratvemulapalli This was intentional, should we backport all of the communication mechanism commits to 2.x?

**Comment by saratvemulapalli** [comment]
> @saratvemulapalli This was intentional, should we backport all of the communication mechanism commits to 2.x?

Yes we should. If we have to release AD extension on 2.x line these changes should be in 2.x. 
Also to run performance runs for AD extension in 2.x, we have to backport them.

**Pull request merged**
