### PR TITLE
Update maven publication to include cksums.

### LINKED ISSUE #79: [BUG] Incorrect maven artifacts published
Similar to https://github.com/opensearch-project/common-utils/issues/88, this was broken post 1.1 (in https://github.com/opensearch-project/job-scheduler/pull/72) to attempt to fix publishing maven signature files.

### PR DESCRIPTION
**Pull request by mch2**
Signed-off-by: Marc Handalian <handalm@amazon.com>

### Description
This change adds a task to publish to a local staging repo under build/ that includes cksums.  It also updates build.sh to use this new task and copy the contents of the staging repo to the output directory.
The maven publish plugin will not include these cksums when publishing to maven local but will when published to a separate folder.

```
/scripts/build.sh -v 1.2.0 -s true
```

```
~/workspace/job-scheduler (maven)$ find artifacts/maven/org/opensearch/opensearch-job-scheduler-spi
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/maven-metadata.xml.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/maven-metadata.xml
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-javadoc.jar.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-javadoc.jar.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.pom.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-sources.jar.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.pom.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.pom.sha1
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.jar.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-sources.jar.sha1
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.jar
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/maven-metadata.xml.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.pom.sha1
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.jar.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.pom.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-sources.jar.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-javadoc.jar.sha1
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.jar.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-sources.jar
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.pom
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-javadoc.jar.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-javadoc.jar
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-sources.jar.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/maven-metadata.xml
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.pom.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.jar.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.jar.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.pom.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/maven-metadata.xml.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.jar.sha1
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.jar.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-javadoc.jar.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.pom
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-sources.jar.sha1
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-sources.jar.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.jar.sha1
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-javadoc.jar.sha256
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-javadoc.jar.sha1
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/maven-metadata.xml.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-sources.jar.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/maven-metadata.xml.sha1
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1-javadoc.jar.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-sources.jar
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210704-1.pom.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-sources.jar.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2.jar
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/1.2.0.0-SNAPSHOT/opensearch-job-scheduler-spi-1.2.0.0-20211103.210801-2-javadoc.jar
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/maven-metadata.xml.sha512
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/maven-metadata.xml.md5
artifacts/maven/org/opensearch/opensearch-job-scheduler-spi/maven-metadata.xml.sha1
```
 
### Issues Resolved
closes #79 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]

**Comment by dblock** [comment]
What is the `-20211103.210704` appendage? I don't see that in the old output.

Will you please update https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#include-checksums-in-maven-publications as well?

**Comment by dblock** [comment]
Needs to be backported into 1.x/1.2 as well if that's a thing.

**Comment by mch2** [comment]
> What is the `-20211103.210704` appendage? I don't see that in the old output. Is it just because we're building snapshot in the example?
> 

Yes this will only appear for snapshot builds.  Snapshots that are not published to mavenLocal will include this timestamp.  I haven't been able to figure out how to turn this off but I don't think it will be an issue.

> Will you please update https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#include-checksums-in-maven-publications as well?

ack & looking at backports...

**Comment by dblock** [comment]
I believe this removed job-scheduler.jar from publishing tp maven, and looking at #114 it may actually be needed.

**Comment by mch2** [comment]
The base job-scheduler jar was skipped because only SPI was historically published as part of odfe.  
I've updated this as part of #117 to be included and configured its pom properly for maven central.

**Pull request merged**
