### PR TITLE
Update sample-extension-plugin BWC version to 2.14.0

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Coming from the version increment PR 2.14.0 PR https://github.com/opensearch-project/job-scheduler/pull/605.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Adding @cwperks @joshpalis @dbwiddis to please check this.
@bbarani

**Comment by cwperks** [comment]
@prudhvigodithi Should this value be trailing by one minor version? If this is updated, the bwc tests would run with 2.14 -> 2.14.

Is there a failing check?

**Comment by prudhvigodithi** [comment]
@cwperks thanks for checking this PR. I just followed the same way on how the bwc is managed for `sample-extension-plugin`, example https://github.com/opensearch-project/job-scheduler/pull/528. Since the 2.x is already [incremented](https://github.com/opensearch-project/job-scheduler/pull/605) to 2.14.0 I have updated main (3.0.0) to 2.14.0.

**Comment by cwperks** [comment]
Got it, thank you Prudhvi! This change LGTM. Should we look into implementing an automatic version increment for this?

**Review by cwperks — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Yes @cwperks I'm planning to leverage the gradle [updateVersion](https://github.com/opensearch-project/job-scheduler/blob/main/build.gradle#L338-L347) task for this, but I'm curious if we need this `sample-extension-plugin` once we have proper unit and integ tests added.

**Comment by cwperks** [comment]
IMO the sample-extension-plugin is a good reference for plugin developers wanting to incorporate scheduled jobs in their plugins. They can use sample-extension-plugin as a reference on how to implement the JobSchedulerExtension extension point and how to use the locking service.

**Comment by prudhvigodithi** [comment]
Make sense, let me open an new issue and add more details on onboarding job-scheduler to integration testing pipeline and also in improving the code coverage.

**Pull request merged**
