### PR TITLE
Use to use the build CI image in ci.yml

### PR DESCRIPTION
**Pull request by prudhvigodithi**
### Description
Use to use the build CI image in ci.yml.
 
### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-build/issues/3966
Closes https://github.com/opensearch-project/job-scheduler/issues/524
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prudhvigodithi** [comment]
Hey @peterzhuamazon can you please take a look at this PR?
I assume as suggested in [meta issue](https://github.com/opensearch-project/opensearch-build/issues/3966) need to only the build and test workflows and not the [bwc test workflows](https://github.com/opensearch-project/job-scheduler/blob/main/.github/workflows/bwc-test-workflow.yml), also did not use the option `options: --user root` as there are no packages that needs to be installed for job-scheduler.
Thank you 

Adding @joshpalis @minalsha @bbarani

**Comment by prudhvigodithi** [comment]
Looks like we need the `options: --user root` to allow the repo checkout inside the container, added back.

**Review by peterzhuamazon — APPROVED** [review]

**Comment by prudhvigodithi** [comment]
Hey @joshpalis can you please take a look at the failed tests ? are they flaky ?

**Comment by joshpalis** [comment]
@prudhvigodithi , yes this is a flaky test, which has been identified in the handoff document. 
```
org.opensearch.jobscheduler.sampleextension.SampleJobRunnerIT > testJobUpdateWithRescheduleJob FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at __randomizedtesting.SeedInfo.seed([14A61049E22DA007:C548E907BD31869D]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.jobscheduler.sampleextension.SampleJobRunnerIT.testJobUpdateWithRescheduleJob(SampleJobRunnerIT.java:81)
REPRODUCE WITH: ./gradlew ':opensearch-job-scheduler-sample-extension:integTest' --tests "org.opensearch.jobscheduler.sampleextension.SampleJobRunnerIT.testJobUpdateWithRescheduleJob" -Dtests.seed=14A61049E22DA007 -Dtests.security.manager=false -Dtests.locale=hr-HR -Dtests.timezone=America/Indiana/Indianapolis -Druntime.java=11
```

I'll re-run the failed checks

**Review by cwperks — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Hi @prudhvigodithi could you help backport this to 2.x?
Thanks.

**Comment by prudhvigodithi** [comment]
I have created a backport PR https://github.com/opensearch-project/job-scheduler/pull/535
@peterzhuamazon @joshpalis @cwperks please take a look.

**Pull request merged**
