### PR TITLE
Removed publishPluginZipPublicationToMavenLocal from exclude list

### PR DESCRIPTION
**Pull request by owaiskazi19**
### Description
Removed publishPluginZipPublicationToMavenLocal from exclude list
 
### Issues Resolved
Coming from https://github.com/opensearch-project/skills/issues/178#issuecomment-1931244149
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dbwiddis — APPROVED** [review]

**Comment by vibrantvarun** [comment]
Can you once test if this publishing the zip on all the places required on sonatype?

I remember this a way to check on the machine as well.

/opensearch-job-scheduler-spi
/opensearch-job-scheduler
/plugin/opensearch-job-scheduler

**Comment by prudhvigodithi** [comment]
Seen the artifacts in right place.
```
org/opensearch/opensearch-job-scheduler/2.12.0.0
org/opensearch/opensearch-job-scheduler-spi/2.12.0.0
org/opensearch/plugin/opensearch-job-scheduler/2.12.0.0
/.m2/repository/org/opensearch/plugin/opensearch-job-scheduler/2.12.0.0 ---> Added the JS zip to the locale maven with with this PR
```

But missing `~/.m2/repository/org/opensearch/opensearch-job-scheduler/2.12.0.0/`.

**Review by prudhvigodithi — CHANGES_REQUESTED** [review]
Can you test and see if `~/.m2/repository/org/opensearch/opensearch-job-scheduler/2.12.0.0/` is missing from your end as well?

**Comment by owaiskazi19** [comment]
Verified the below @vibrantvarun 
```
ls snapshots/org/opensearch/plugin/opensearch-job-scheduler/3.0.0.0-SNAPSHOT/
maven-metadata.xml                                             opensearch-job-scheduler-3.0.0.0-20240209.023010-1.pom         opensearch-job-scheduler-3.0.0.0-20240209.023010-1.zip
maven-metadata.xml.md5                                         opensearch-job-scheduler-3.0.0.0-20240209.023010-1.pom.md5     opensearch-job-scheduler-3.0.0.0-20240209.023010-1.zip.md5
maven-metadata.xml.sha1                                        opensearch-job-scheduler-3.0.0.0-20240209.023010-1.pom.sha1    opensearch-job-scheduler-3.0.0.0-20240209.023010-1.zip.sha1
maven-metadata.xml.sha256                                      opensearch-job-scheduler-3.0.0.0-20240209.023010-1.pom.sha256  opensearch-job-scheduler-3.0.0.0-20240209.023010-1.zip.sha256
maven-metadata.xml.sha512                                      opensearch-job-scheduler-3.0.0.0-20240209.023010-1.pom.sha512  opensearch-job-scheduler-3.0.0.0-20240209.023010-1.zip.sha512
```

```
ls snapshots/org/opensearch/opensearch-job-scheduler/3.0.0.0-SNAPSHOT/
maven-metadata.xml                                                     opensearch-job-scheduler-3.0.0.0-20240209.022920-1.jar
maven-metadata.xml.md5                                                 opensearch-job-scheduler-3.0.0.0-20240209.022920-1.jar.md5
maven-metadata.xml.sha1                                                opensearch-job-scheduler-3.0.0.0-20240209.022920-1.jar.sha1
maven-metadata.xml.sha256                                              opensearch-job-scheduler-3.0.0.0-20240209.022920-1.jar.sha256
maven-metadata.xml.sha512                                              opensearch-job-scheduler-3.0.0.0-20240209.022920-1.jar.sha512
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-javadoc.jar         opensearch-job-scheduler-3.0.0.0-20240209.022920-1.module
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-javadoc.jar.md5     opensearch-job-scheduler-3.0.0.0-20240209.022920-1.module.md5
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-javadoc.jar.sha1    opensearch-job-scheduler-3.0.0.0-20240209.022920-1.module.sha1
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-javadoc.jar.sha256  opensearch-job-scheduler-3.0.0.0-20240209.022920-1.module.sha256
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-javadoc.jar.sha512  opensearch-job-scheduler-3.0.0.0-20240209.022920-1.module.sha512
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-sources.jar         opensearch-job-scheduler-3.0.0.0-20240209.022920-1.pom
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-sources.jar.md5     opensearch-job-scheduler-3.0.0.0-20240209.022920-1.pom.md5
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-sources.jar.sha1    opensearch-job-scheduler-3.0.0.0-20240209.022920-1.pom.sha1
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-sources.jar.sha256  opensearch-job-scheduler-3.0.0.0-20240209.022920-1.pom.sha256
opensearch-job-scheduler-3.0.0.0-20240209.022920-1-sources.jar.sha512  opensearch-job-scheduler-3.0.0.0-20240209.022920-1.pom.sha512
```

```
ls snapshots/org/opensearch/opensearch-job-scheduler-spi/3.0.0.0-SNAPSHOT/
maven-metadata.xml                                                         opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1.pom.sha256
maven-metadata.xml.md5                                                     opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1.pom.sha512
maven-metadata.xml.sha1                                                    opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-javadoc.jar
maven-metadata.xml.sha256                                                  opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-javadoc.jar.md5
maven-metadata.xml.sha512                                                  opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-javadoc.jar.sha1
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-javadoc.jar         opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-javadoc.jar.sha256
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-javadoc.jar.md5     opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-javadoc.jar.sha512
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-javadoc.jar.sha1    opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-sources.jar
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-javadoc.jar.sha256  opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-sources.jar.md5
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-javadoc.jar.sha512  opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-sources.jar.sha1
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-sources.jar         opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-sources.jar.sha256
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-sources.jar.md5     opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2-sources.jar.sha512
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-sources.jar.sha1    opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2.jar
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-sources.jar.sha256  opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2.jar.md5
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1-sources.jar.sha512  opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2.jar.sha1
opensearch-job-scheduler-spi-3.0.0.0-20240209.022529-1.jar                 opensearch-job-scheduler-spi-3.0.0.0-20240209.022856-2.jar.sha256
```

**Comment by owaiskazi19** [comment]
> Can you test and see if `~/.m2/repository/org/opensearch/opensearch-job-scheduler/2.12.0.0/` is missing from your end as well?

This is a PR to main, right?

**Comment by vibrantvarun** [comment]
Me and @owaiskazi19 have tested the artifact publishing on the local machine.

/opensearch-job-scheduler-spi  jar gets published
/opensearch-job-scheduler zip gets published
/opensearch-job-scheduler zip gets published

cc: @prudhvigodithi

**Comment by vibrantvarun** [comment]
I think the artifact in .m2 path is missing because we do not have publishToMavenLocal in the maven-publish.yml

**Comment by prudhvigodithi** [comment]
@owaiskazi19 I have your changes against `2.12`

Before the change, In local maven (`org.opensearch`) I see:
```
opensearch-job-scheduler/   opensearch-job-scheduler-sample-extension/  opensearch-job-scheduler-spi/  
```

After the change, In local maven (`org.opensearch`) I see:

```
opensearch-job-scheduler-sample-extension/ opensearch-job-scheduler-spi/ 
```

**Comment by owaiskazi19** [comment]
DO NOT MERGE THIS. Created https://github.com/opensearch-project/job-scheduler/pull/582 to copy the zips for now.

**Comment by peterzhuamazon** [comment]
> DO NOT MERGE THIS. Created #582 to copy the zips for now.

Converted to draft just in case.

**Comment by prudhvigodithi** [comment]
Closing this PR in favor of https://github.com/opensearch-project/job-scheduler/pull/584.

**Pull request closed without merging**
