### PR TITLE
Backport: Update build.sh script to include optional platform param (#99)

### PR DESCRIPTION
**Pull request by gaiksaya**
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>

### Description
Backport PR: #99 
Add optional platform param sent by build workflow. This param is optional in this script but will always be sent by the workflow.
 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by gaiksaya** [comment]
@dblock @peternied please review. Not sure what the link checker error is here.

**Comment by peternied** [comment]
Why are we backporting this to 1.1?

**Comment by gaiksaya** [comment]
> Why are we backporting this to 1.1?

Because 1.1 branch is used to build these artifacts? Once we backport this we can delete the scripts from opensearch-build repo so that this script is executed. 
Correct me if I am wrong @dblock

**Comment by peternied** [comment]
> > Why are we backporting this to 1.1?
> 
> 
> 
> Because 1.1 branch is used to build these artifacts. Once we backport this we can delete the scripts from opensearch-build repo so that this script is executed. 
> 
> Correct me if I am wrong @dblock 

I am uneasy with making changes to component branches that already released. This seems like a candidate for back comparability support.

**Comment by gaiksaya** [comment]
My bad, it should have been 1.2. Closing this PR

**Pull request closed without merging**
