### PR TITLE
Move main to OpenSearch 3.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Move main to OpenSearch 3.0.0-SNAPSHOT
 
### Issues Resolved
Follow up on https://github.com/opensearch-project/job-scheduler/pull/208#issuecomment-1233427519
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock moving to `3.0.0-SNAPSHOT`, thanks!

**Review by joshpalis — APPROVED** [review]

**Comment by dblock** [comment]
The BCW test is failing on https://github.com/opensearch-project/OpenSearch/issues/3615

**Comment by dblock** [comment]
I made a bit of progress in https://github.com/opensearch-project/job-scheduler/pull/242, but check out https://github.com/opensearch-project/OpenSearch/issues/3615#issuecomment-1247100028. I think we need 2.4.0 for bcw to work which doesn't seem right, should we relax that limitation and allow 3.0 to join any 2.x cluster?

**Comment by dblock** [comment]
Done in https://github.com/opensearch-project/job-scheduler/pull/242

**Pull request closed without merging**
