### PR TITLE
Increment to 3.0.0-snapshot

### LINKED ISSUE #205: Implement OpenSearch core branching strategy
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

### PR DESCRIPTION
**Pull request by amitgalitz**
Signed-off-by: Amit Galitzky <amgalitz@amazon.com>

### Description
increment repo to 3.0.0-SNAPSHOT
 
### Issues Resolved
#205 
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by sbcd90** [comment]
the bwc tests fail with a similar error mentioned in [BWC Tests failure](https://github.com/opensearch-project/OpenSearch/issues/3615).
will follow the pr.

**Comment by ohltyler** [comment]
@sbcd90 any update on BWC failures here?

**Comment by sbcd90** [comment]
@ohltyler , i still face the same error. 
updated the issue with more details on the exception.[Bwc Test Failure](https://github.com/opensearch-project/OpenSearch/issues/3615)

**Comment by dblock** [comment]
I'll re-raise after https://github.com/opensearch-project/job-scheduler/pull/208

**Pull request closed without merging**
